config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :games do
	resources :rounds
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :users
  has_many :rounds
  accepts_nested_attributes_for :users , :allow_destroy => true
  def winner
	 max_score = self.users.map(&:total_score).max
   self.users.select{|player| player.total_score == max_score}.first
  end
  end

        
 
 

app/models/round.rb
class Round < ApplicationRecord
	belongs_to :game
	has_many :scores
end

app/models/score.rb
class Score < ApplicationRecord
	belongs_to :user
	belongs_to :round
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :game
	has_many :scores
	
	def total_score
		score = self.scores.sum(:value)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def create
    @game = Game.new(game_params)
    @game.save
    redirect_to @game
  end

    def new
      @game = Game.new
    end

    def show
      @game = Game.find(params[:id])
      @round = Round.new
      @scores = Score.all
      @winner = @game.winner
    end

    private

    def game_params
      params.require(:game).permit(:Game_name, :No_of_players, :status, users_attributes: [:name,:_destroy])
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
	def new
        @round = Round.new
    end

    def create
        @game = Game.find(params[:game_id])
        @round = @game.rounds.create
        params[:score].each do |user_id, value|
        	@round.scores.create(user_id: user_id, value: value)
        end
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
	def index
      @scores = Score.all
  end

  def new
      @score = Score.new
  end

  def show
      @score = Score.find(params[:id])
  end

  def create
    respond_to do |format|
    format.js
    format.html
      end
  end

  private
  def score_params
    params.require(:score).permit(:value, :round_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_score.html.erb
<div class="row">
    <% game.users.each do |player| %>
        <div class="col-md-3"><%= player.scores.sum(:value) %></div>
    <% end %>
</div>

app/views/games/index.html.erb
<html>
  <head>
  <style>
    body{
      background-image: url("https://hdwallsource.com/img/2014/9/blur-26347-27038-hd-wallpapers.jpg");
    }
  </style>
  </head>
<body>
<div class="container" style="background-color:beige;font-style:italic;margin-top:30px;">
    <div class="panel panel-default">
    <div class="panel-heading"><b>Game List</b>
      <div class="col-xs-12 text-right">
        <%= link_to "Game + ", new_game_path, class: "btn btn-warning btn-sm "%>
      </div>
    </div>

    <table class="table table-striped">
      <thead>
        <tr>
          <th class="col-xs-3">Game</th>
          <th class="col-xs-3">No of Players</th>
        </tr>
      </thead>
      <tbody>
        <tr><% @games.each do |games| %>
          <tr> 
            <td><%= games.Game_name %></td>
            <td><%= games.users.count %></td>
            <td><%= link_to "Add Score", game_path(games), class: "btn btn-success btn-sm "%></td>
          </tr><%end%></tbody>
    </div>
  </div>
</tr></body></html>

app/views/games/new.html.erb
<html>
  <head>
    <style>
      h1{
        text-align: center;
      }
      body{
        background-image: url("https://hdwallsource.com/img/2014/9/blur-26347-27038-hd-wallpapers.jpg");
      }
    </style>
  <h1>ADD NEW GAME</h1>
  <div class="container" style="max-width:500px; max-height: 500px;">
    <div class="grid-container">
      <%= nested_form_for @game do |form| %>
      <p>
        <%= form.label :'Game_name' %><br>
        <%= form.text_field :Game_name %>
      </p>
        <%= form.fields_for :users do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.link_to_remove "Remove", class: "text-danger" %>
        <%end%>
      <p><%= form.link_to_add "Add", :users , class: "text-info"%></p>
          <%= form.submit 'Save', class: "btn btn-success"%>
          <%= link_to "Back", games_path, class: "btn btn-success btn-xs"%>
          <%end%>
      </div>
    </div>
  </body> 
</html>

app/views/games/show.html.erb
<html>
<head>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script> 
      function winner() { 
        alert("The Winner is: <%= @winner.name%>");
        alert("The End!!") 
      } 
    </script>
  <style>
    h1{
      text-align: center;
    }
    body{
      background-image: url("https://hdwallsource.com/img/2014/9/blur-26347-27038-hd-wallpapers.jpg");
    }
  </style>
  <br>
  <h1>Score Adder</h1>
</head>
<body>
<%=form_tag "/games/#{@game.id}/rounds", method: :post, remote: true do%>
<br><div class="container">
 <div class="grid-container">
    <% @game.users.each do |player| %>
      <div class="col-md-3">
        <strong><%= player.name %></strong><br> 
        <%= text_field_tag "score[#{player.id}]" %>
      </div>
    <% end %>
    <%end%>
    <%= submit_tag 'Add score' , class: "btn btn-warning btn-xs"%>
    <div id="scores">
      <strong>Total</strong><br>
      <%=  render 'score', game: @game %>
    </div>
    <br>
  </div>
</div>
</div>
<br>
  <div id="winner" style="text-align:center;">
  <%= link_to "Back", games_path, class: "btn btn-success btn-xs "%>
  <button onclick ="winner()" class="btn btn-danger"> End Game </button >
  </div>
</body>
 </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScoreboardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rounds/create.js.erb
$('#scores').html('<%= j render partial: "games/score", locals: {game: @game} %>');